# Generated by Django 5.0 on 2025-11-18 16:43

import django.db.models.deletion
import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file_path", models.FileField(upload_to="uploads/%Y/%m/%d/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("docx", "DOCX"),
                            ("txt", "TXT"),
                            ("jpg", "JPG"),
                            ("jpeg", "JPEG"),
                            ("png", "PNG"),
                        ],
                        max_length=10,
                    ),
                ),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                ("language", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "Uploaded"),
                            ("PROCESSING", "Processing"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                        ],
                        default="UPLOADED",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("num_chunks", models.IntegerField(default=0)),
                (
                    "num_pages",
                    models.IntegerField(
                        default=0, help_text="Number of pages (if applicable)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="documents_d_status_07369e_idx"
                    ),
                    models.Index(
                        fields=["-created_at"], name="documents_d_created_71dced_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DocumentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "index",
                    models.IntegerField(help_text="Chunk index within the document"),
                ),
                ("text", models.TextField(help_text="Chunk text content")),
                (
                    "page_number",
                    models.IntegerField(
                        blank=True, help_text="Page number if applicable", null=True
                    ),
                ),
                ("embedding", pgvector.django.VectorField(dimensions=768)),
                ("char_count", models.IntegerField(default=0)),
                ("token_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="documents.document",
                    ),
                ),
            ],
            options={
                "ordering": ["document", "index"],
                "indexes": [
                    models.Index(
                        fields=["document", "index"],
                        name="documents_d_documen_538f7c_idx",
                    )
                ],
                "unique_together": {("document", "index")},
            },
        ),
    ]
